#插件作者：幻梦official
#该插件禁止任何倒卖！
#开源地址: https://github.com/huanmeng-official/

#该项为欢迎人物
Characters: '[幻梦娘]'
#该项为欢迎语句
Tips: '欢迎加入服务器！(≧^.^≦)喵~'
#该项为睡觉时的提示语句
Sleep: '这么晚才睡嘛？要好好睡觉哦ヾ(≧O≦)〃'
#该项为离开床时的提示语句
Getup: '这么早就起床嘛？不如再睡一觉吧✧(◍˃̶ᗜ˂̶◍)✩'
#该句为玩家说脏话时的警告语句
Alert: '请注意文明哦(ꐦ ಠ 皿 ಠ) '
#该项为彩蛋触发关键词 #1
PaintEggWord-1: '彩蛋'
#该项为彩蛋触发关键词 #2
PaintEggWord-2: '开摆'
#该项为彩蛋提示人物
EggCharacters: '[幻梦娘]'
#该项为彩蛋内容 #1
PEgg-one: '恭喜你触发了彩蛋，但毫无卵用'
#该项为彩蛋内容 #2
PEgg-two: '恭喜你触发了彩蛋，但毫无卵用'