#插件作者：幻梦official
#该插件禁止任何倒卖！
#开源地址: https://github.com/HuanMeng-official/AutomaticWelcomePlugin
#插件配置：false（关闭）  true（开启）

#脏话屏蔽开关
PlayChatEvent: false
#烂梗屏蔽开关
Stem: false
#彩蛋触发语句拦截（不在聊天栏显示，依旧触发彩蛋）
PaintEgg: false

#该项为欢迎人物
Characters: '[幻梦娘]'
#该项为欢迎语句的服务器提示名称
#[幻梦娘]欢迎xxx加入'服务器'  您所填的是''中的服务器名称
Server: '服务器'
#该项为睡觉时的提示语句
Sleep: '这么晚才睡嘛？要好好睡觉哦ヾ(≧O≦)〃'
#该项为离开床时的提示语句
Getup: '这么早就起床嘛？不如再睡一觉吧✧(◍˃̶ᗜ˂̶◍)✩'
#该句为玩家说脏话时的警告语句
Alert: '请注意文明哦(ꐦ ಠ 皿 ಠ) '
#该项为玩家发送烂梗的警告语句
Stemalert: '请适度玩梗 →_→'

#该项为彩蛋提示人物
EggCharacters: '[幻梦娘]'
#该项为彩蛋触发关键词 #1
PaintEggWord-1: '彩蛋'
#该项为彩蛋内容 #1
PEgg-one: '恭喜你触发了彩蛋，但毫无卵用'
#该项为彩蛋触发关键词 #2
PaintEggWord-2: '彩蛋'
#该项为彩蛋内容 #2
PEgg-two: '恭喜你触发了彩蛋，但毫无卵用'
#该项为彩蛋触发关键词 #3
PaintEggWord-3: '彩蛋'
#该项为彩蛋内容 #3
PEgg-three: '恭喜你触发了彩蛋，但毫无卵用'
#该项为彩蛋触发关键词 #4
PaintEggWord-4: '彩蛋'
#该项为彩蛋内容 #4
PEgg-four: '恭喜你触发了彩蛋，但毫无卵用'