name: AutomaticWelcome
version: '${project.version}'
main: huanmeng.automaticwelcome.AutomaticWelcome
api-version: 1.16
softdepend:
  - PlaceholderAPI
commands:
  tps:
    description: Viewer the server TPS
  automatic:
    description: Check if the plugin is started
  gm0:
    description: Set Player Game Mode Survival
  gm1:
    description: Set Player Game Mode Creative
  gm2:
    description: Set Player Game Mode Adventure
  gm3:
    description: Set Player Game Mode Spectator
permissions:
  aw.huanmeng.op:
    description: Permission
    default: op
