name: AutomaticWelcome
version: '${project.version}'
main: huanmeng.automaticwelcome.AutomaticWelcome
api-version: 1.16
commands:
  automatic:
    description: Check if the plugin is started
  gm0:
    description: Set Player Game Mode Survival
  gm1:
    description: Set Player Game Mode Creative
  gm2:
    description: Set Player Game Mode Adventure
  gm3:
    description: Set Player Game Mode Spectator
